### ISSUE TITLE
Token stealer

### ISSUE THREAD

**Issue by 123345666777777777777777777777777** [notzastix/betastar.js-examples#1]
My friend said there is a code to steal tokens from others in blacket. Can u confirm?

**Comment by notzastix** [comment]
no lol

**Comment by 123345666777777777777777777777777** [comment]
Can u try to make one

**Comment by notzastix** [comment]
no, mainly cause that isnt possible + i have no need  / want to

**Comment by 123345666777777777777777777777777** [comment]
Ok
